name: deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: setup node v14
        uses: actions/setup-node@v1.4.4
        with:
          node-version: 14.x
      - name: npm install
        run: npm install
      - name: build js
        run: npm run build-prod
      - name: relase to gh-pages
        run: |
          git config --global user.name "Github Action"
          git config --global user.email "<>"
          git --work-tree dist/ checkout --orphan gh-pages
          rm dist/.gitkeep
          git --work-tree dist/ add --all
          git commit -m "[ci skip] release $(date)"
          git push --force --set-upstream origin gh-pages